-- MANUAL TEST RESULTS (Original Query)
SELECT 
    r.RUNSET_ID,
    s.SAMPLE_ID,
    p.NAME as CHARACTERISTIC_NAME,
    p.DISPLAY_NAME as CHARACTERISTIC_DISPLAY_NAME,
    pv.VALUE_NUMERIC,
    pv.VALUE_STRING as RESULT,
    pv.VALUE_TEXT as FORMATTED_RESULT,
    pv.INTERPRETATION as COMPOSE_DETAILS,
    rt.LIFE_CYCLE_STATE as TASK_STATUS,
    'MANUAL' as RESULT_SOURCE
FROM COR_PARAMETER_VALUE pv
JOIN COR_PARAMETER p ON pv.PARENT_IDENTITY = p.ID
JOIN REQ_TASK_PARAMETER rtp ON p.ID = rtp.PARAMETER_ID
JOIN REQ_TASK rt ON rtp.TASK_ID = rt.ID
JOIN REQ_RUNSET r ON rt.RUNSET_ID = r.ID
LEFT JOIN SAM_SAMPLE s ON s.SAMPLE_ID = REGEXP_SUBSTR(rt.SAMPLE_LIST, '[^,]+', 1, pv.ITEM_INDEX + 1)
WHERE pv.VALUE_KEY = 'A'
  AND r.RUNSET_ID = 'TP002'

UNION ALL

-- EQUIPMENT MEASUREMENT RESULTS (New Query)
SELECT 
    r.RUNSET_ID,
    s.SAMPLE_ID,
    MAX(CASE WHEN pv.VALUE_STRING IS NOT NULL THEN pv.VALUE_STRING END) as CHARACTERISTIC_NAME,
    MAX(CASE WHEN pv.VALUE_STRING IS NOT NULL THEN pv.VALUE_STRING END) as CHARACTERISTIC_DISPLAY_NAME,
    MAX(CASE WHEN pv.VALUE_NUMERIC IS NOT NULL THEN pv.VALUE_NUMERIC END) as VALUE_NUMERIC,
    TO_CHAR(MAX(CASE WHEN pv.VALUE_NUMERIC IS NOT NULL THEN pv.VALUE_NUMERIC END)) as RESULT,
    TO_CHAR(MAX(CASE WHEN pv.VALUE_NUMERIC IS NOT NULL THEN pv.VALUE_NUMERIC END)) as FORMATTED_RESULT,
    NULL as COMPOSE_DETAILS,
    rt.LIFE_CYCLE_STATE as TASK_STATUS,
    'EQUIPMENT' as RESULT_SOURCE
FROM COR_PARAMETER_VALUE pv
JOIN PEX_PROC_ELEM_EXEC_PARAM peep ON peep.ID = pv.PARENT_IDENTITY
JOIN PEX_PROC_ELEM_EXEC pee ON pee.ID = peep.PARENT_ID
JOIN PEX_PROC_EXEC pe ON pe.ID = pee.PARENT_ID
JOIN RES_RETRIEVAL_CONTEXT ctx ON ctx.CONTEXT = 
    'urn:pexelement:' || LOWER(
        SUBSTR(RAWTOHEX(pee.ID), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(pee.ID), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(pee.ID), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(pee.ID), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(pee.ID), 21, 12)
    )
JOIN RES_MEASUREMENTSAMPLE ms ON ms.CONTEXT_ID = ctx.ID
JOIN RES_MEASUREMENT m ON m.ID = ms.MEASUREMENT_ID
JOIN SAM_SAMPLE s ON s.ID = ms.MAPPED_SAMPLE_ID
JOIN REQ_TASK rt ON INSTR(',' || rt.SAMPLE_LIST || ',', ',' || s.SAMPLE_ID || ',') > 0
JOIN REQ_RUNSET r ON r.ID = rt.RUNSET_ID
WHERE r.RUNSET_ID = 'TP002'
GROUP BY r.RUNSET_ID, s.SAMPLE_ID, rt.LIFE_CYCLE_STATE, peep.ID, peep.SOURCE_POSITION
HAVING MAX(CASE WHEN pv.VALUE_NUMERIC IS NOT NULL THEN pv.VALUE_NUMERIC END) IS NOT NULL

ORDER BY SAMPLE_ID, CHARACTERISTIC_NAME;