INSERT INTO onelab_result_report (
  "Sample Name",
  "Sample ID",
  "Sample Status",
  "Master Sample ID",
  "Sampling point",
  "Sampling point description",
  "LINE-1",
  "Owner",
  "Product Code",
  "Product Description",
  "CIG_PRODUCT_CODE",
  "CIG_PRODUCT_DESCRIPTION",
  "Spec_Group",
  "Task Plan Project",
  "Task Plan ID",
  "Task Plan Creation Date",
  "Task Status",
  "Characteristic",
  "Result",
  "Formatted result",
  "Result entered",
  "Result Source",
  "UOM",
  "Task Plan Project Plan"
)
SELECT
  "Sample Name",
  "Sample ID",
  "Sample Status",
  "Master Sample ID",
  "Sampling point",
  "Sampling point description",
  "LINE-1",
  "Owner",
  "Product Code",
  "Product Description",
  "CIG_PRODUCT_CODE",
  "CIG_PRODUCT_DESCRIPTION",
  "Spec_Group",
  "Task Plan Project",
  "Task Plan ID",
  "Task Plan Creation Date",
  "Task Status",
  "Characteristic",
  "Result",
  "Formatted result",
  "Result entered",
  "Result Source",
  "UOM",
  "Task Plan Project Plan"
FROM vw_onelab_result_source;